variables:
  GIT_SUBMODULE_STRATEGY: none
  CI_DISPOSABLE_ENVIRONMENT: "true"

image: blockstream/gcloud-docker@sha256:31c1a01d143558f0ba5677d121891a958fa600195679fe325980ec72e5264f2a
stages:
  - build
  - deploy

before_script:
  - TMPF=$(mktemp) || exit 1
  - echo $GCLOUD_KEY > $TMPF
  - export GOOGLE_APPLICATION_CREDENTIALS=$TMPF # used by tf
  - gcloud auth activate-service-account --key-file=$TMPF
  - gcloud auth list
  - gcloud --version

build_ionosphere:
  only:
    - master@satellite/ionosphere
  stage: build
  script:
    - docker build -f Dockerfile -t us.gcr.io/blockstream-store/ionosphere:latest -t us.gcr.io/blockstream-store/ionosphere:$CI_COMMIT_SHA .
    - docker push us.gcr.io/blockstream-store/ionosphere:$CI_COMMIT_SHA
    - docker push us.gcr.io/blockstream-store/ionosphere:latest

deploy_ionosphere:
  stage: deploy
  only:
    - tags@satellite/ionosphere
  script:
    - (cd terraform && terraform init)
    - (cd terraform && terraform destroy
        -target module.blc.google_compute_instance_group_manager.blc
        -auto-approve)
    - (cd terraform && terraform apply
        -var "ionosphere_docker=us.gcr.io/blockstream-store/ionosphere:$CI_COMMIT_SHA"
        -input=false -auto-approve)
